repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort -rc src tests setup.py
        language: system
        types: [python]
      - id: black
        name: black
        entry: black src tests setup.py
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: flake8 src tests setup.py
        language: system
        types: [python]
