repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort anlearn tests setup.py
        language: system
        types: [python]
      - id: black
        name: black
        entry: black anlearn tests setup.py
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: flake8 anlearn tests setup.py
        language: system
        types: [python]
