version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - epub

python:
  version: 3.8
  install:
    - requirements: requirements/requirements-3.8.txt
    - requirements: requirements/requirements-3.8-docs.txt
    - method: pip
      path: .
