site_name: anlearn - Anomaly learn
site_description: Anomaly detection methods for Python.
site_url: https://www.gaussalgo.com/

repo_name: gaussalgo/anlearn
repo_url: https://github.com/gaussalgo/anlearn

copyright: '<a href="https://www.gaussalgo.com/">Copyright (c) Gauss Algoritmic a.s.</a>'

theme:
  name: material
  palette:
    primary: cyan
    accent: cyan

nav:
  - index.md
  - Anomaly detection methods:
      - loda.md
  - dev-guide.md
  - jupyter-notebooks.md
  - API reference:
      - reference/loda.md
      - reference/stats.md

markdown_extensions:
  - admonition
  - codehilite
  - mdx_truly_sane_lists
  - pymdownx.superfences
  - pymdownx.arithmatex
  - pymdownx.details

extra_css:
  - css/custom.css

extra_javascript:
  - js/mathjax-config.js
  - "https://polyfill.io/v3/polyfill.min.js?features=es6"
  - "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - src/anlearn
